export type BadgeColor = 'amber' | 'red' | 'ocean';

export const events = [
  {
    id: 1,
    date: 'Ven 20 Giu',
    dateEN: 'Fri Jun 20',
    time: '22:00 → 01:00',
    title: 'DJ Matteo Ricci',
    genre: 'Deep House · Afro',
    description: {
      it: 'Una serata di deep house e ritmi afro per aprire il weekend',
      en: 'A night of deep house and afro beats to open the weekend',
    },
    badge: { it: 'QUESTO WEEKEND', en: 'THIS WEEKEND' },
    badgeColor: 'amber' as BadgeColor,
    featured: true,
  },
  {
    id: 2,
    date: 'Sab 21 Giu',
    dateEN: 'Sat Jun 21',
    time: '22:00 → 01:00',
    title: 'RockIsland Summer Opening',
    genre: 'House · Tech House',
    description: {
      it: "Grande serata di apertura dell'estate con ospiti speciali",
      en: 'Grand summer opening night with special guests',
    },
    badge: { it: 'EVENTO SPECIALE', en: 'SPECIAL EVENT' },
    badgeColor: 'red' as BadgeColor,
    featured: true,
  },
  {
    id: 3,
    date: 'Ven 27 Giu',
    dateEN: 'Fri Jun 27',
    time: '22:00 → 01:00',
    title: 'DJ Set: Sara Vento',
    genre: 'Nu-Disco · Funky',
    description: {
      it: 'Nu-disco e funky per una serata che fa ballare tutta la notte',
      en: 'Nu-disco and funky for a night that keeps you dancing',
    },
    badge: null,
    featured: false,
  },
  {
    id: 4,
    date: 'Sab 28 Giu',
    dateEN: 'Sat Jun 28',
    time: '22:00 → 01:00',
    title: 'Adriatic Sunset Party',
    genre: 'Lounge · Chill House',
    description: {
      it: "Dalle 17:30 con aperitivo al tramonto fino all'1 di notte",
      en: 'From 5:30pm with sunset aperitivo through to 1am',
    },
    badge: { it: 'APERITIVO + SERATA', en: 'APERITIVO + NIGHT' },
    badgeColor: 'ocean' as BadgeColor,
    featured: false,
  },
  {
    id: 5,
    date: 'Ven 4 Lug',
    dateEN: 'Fri Jul 4',
    time: '22:00 → 01:00',
    title: 'DJ Marco Solano',
    genre: 'Melodic Techno',
    description: {
      it: "Melodic techno di qualità con uno dei migliori DJ della riviera",
      en: "Quality melodic techno with one of the Riviera's best DJs",
    },
    badge: null,
    featured: false,
  },
  {
    id: 6,
    date: 'Sab 5 Lug',
    dateEN: 'Sat Jul 5',
    time: '22:00 → 01:00',
    title: 'La Notte Bianca sul Molo',
    genre: 'Mixed · All Genres',
    description: {
      it: "La notte più lunga dell'estate. Due DJ. Una notte indimenticabile.",
      en: "The longest night of summer. Two DJs. One unforgettable night.",
    },
    badge: { it: 'SOLD OUT SOON', en: 'SOLD OUT SOON' },
    badgeColor: 'red' as BadgeColor,
    featured: true,
  },
];
